-- DROP DATABASE HOSPITAL;

CREATE DATABASE HOSPITAL;
USE HOSPITAL;

CREATE TABLE IF NOT EXISTS PACIENTE(
CPF VARCHAR(20) PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
DATA_NASCIMENTO DATE NOT NULL);

CREATE TABLE IF NOT EXISTS MEDICO(
CRM INT PRIMARY KEY,
NOME VARCHAR(100) NOT NULL);

CREATE TABLE IF NOT EXISTS DEPARTAMENTO(
ID_DEPARTAMENTO INT PRIMARY KEY,
NOME_DEP VARCHAR(50) NOT NULL,
MEDICO_CRM INT NOT NULL,
FOREIGN KEY (MEDICO_CRM) REFERENCES MEDICO(CRM));

CREATE TABLE IF NOT EXISTS CONSULTA(
NUM_CONSULTA INT PRIMARY KEY,
ANAMNASE VARCHAR(200) NOT NULL,
DATA_HORA_CONSULTA DATETIME NOT NULL,
PACIENTE_CPF VARCHAR(20) NOT NULL,
MEDICO_CRM INT NOT NULL,
FOREIGN KEY (PACIENTE_CPF) REFERENCES PACIENTE(CPF),
FOREIGN KEY (MEDICO_CRM) REFERENCES MEDICO(CRM));
