-- DROP DATABASE RESERVA_VOO;

CREATE DATABASE IF NOT EXISTS RESERVA_VOO;
USE RESERVA_VOO;

CREATE TABLE IF NOT EXISTS PASSAGEIRO(
COD_PASSAGEIRO INT PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
DATA_NASC DATE NOT NULL,
EMAIL VARCHAR(100) NOT NULL);

CREATE TABLE IF NOT EXISTS RESERVA(
COD_RESERVA INT PRIMARY KEY,
DATA_HORA_RESERVA DATETIME NOT NULL);

CREATE TABLE IF NOT EXISTS COMPANHIA(
COD_CIA_AEREA INT PRIMARY KEY,
NOME_CIA VARCHAR(50) NOT NULL);

CREATE TABLE IF NOT EXISTS AVIAO(
PREFIXO_AEREO INT PRIMARY KEY,
MODELO VARCHAR(20) NOT NULL,
ID_CIA_AEREA INT NOT NULL,
CONSTRAINT COMP_AVIAO FOREIGN KEY (ID_CIA_AEREA) REFERENCES COMPANHIA(COD_CIA_AEREA));

CREATE TABLE IF NOT EXISTS AEROPORTO(
PREFIXO_AEROPORTO INT PRIMARY KEY,
NOME_AEROPORTO VARCHAR(20) NOT NULL);

CREATE TABLE IF NOT EXISTS VOO(
ASSENTO_VOO INT NOT NULL,
NUM_VOO INT NOT NULL,
PRIMARY KEY(ASSENTO_VOO, NUM_VOO),
HORA_CHEGADA TIME NOT NULL,
HORA_SAIDA TIME NOT NULL,
ID_RESERVA INT NOT NULL,
PREF_AEROPORTO_CHEGADA INT NOT NULL,
PREF_AEROPORTO_SAIDA INT NOT NULL,
ID_CIA_AEREA INT NOT NULL,
COD_AERONAVE INT NOT NULL,
CONSTRAINT RESERV_VOO FOREIGN KEY (ID_RESERVA) REFERENCES RESERVA(COD_RESERVA),
CONSTRAINT CHEGADA_VOO FOREIGN KEY (PREF_AEROPORTO_CHEGADA) REFERENCES AEROPORTO(PREFIXO_AEROPORTO),
CONSTRAINT SAIDA_VOO FOREIGN KEY (PREF_AEROPORTO_SAIDA) REFERENCES AEROPORTO(PREFIXO_AEROPORTO),
CONSTRAINT CIA_VOO FOREIGN KEY (ID_CIA_AEREA) REFERENCES COMPANHIA(COD_CIA_AEREA),
CONSTRAINT AERONAVE_VOO FOREIGN KEY (COD_AERONAVE) REFERENCES AVIAO(PREFIXO_AEREO));