-- DROP DATABASE HOSPITAL;

CREATE DATABASE HOSPITAL;
USE HOSPITAL;

CREATE TABLE IF NOT EXISTS PACIENTE(
CPF VARCHAR(20) PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
DATA_NASCIMENTO DATE NOT NULL);

CREATE TABLE IF NOT EXISTS MEDICO(
CRM INT NOT NULL,
UF CHAR(2) NOT NULL,
PRIMARY KEY(CRM, UF),
NOME VARCHAR(100) NOT NULL,
ID_DEPART INT NOT NULL,
CONSTRAINT MED_DEP FOREIGN KEY (ID_DEPART) REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO));

CREATE TABLE IF NOT EXISTS DEPARTAMENTO(
ID_DEPARTAMENTO INT PRIMARY KEY,
NOME_DEP VARCHAR(50) NOT NULL);

CREATE TABLE IF NOT EXISTS CONSULTA(
NUM_CONSULTA INT PRIMARY KEY,
ANAMNASE VARCHAR(200) NOT NULL,
DATA_HORA_CONSULTA DATETIME NOT NULL,
PACIENTE_CPF VARCHAR(20) NOT NULL,
MEDICO_CRM INT NOT NULL,
UF CHAR(2) NOT NULL,
CONSTRAINT UF_CRM FOREIGN KEY (MEDICO_CRM, UF) REFERENCES MEDICO(CRM, UF),
FOREIGN KEY (PACIENTE_CPF) REFERENCES PACIENTE(CPF));
